//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace SmartSesnor
{
    // Type created for JSON at <<root>>
    [DataContractAttribute()]
    public partial class SensorList
    {
        
        [DataMemberAttribute()]
        public string status;
        
        [DataMemberAttribute()]
        public SensorListMessage message;
    }

    // Type created for JSON at <<root>> --> message
    [DataContractAttribute(Name="message")]
    public partial class SensorListMessage
    {
        
        [DataMemberAttribute()]
        public string current_parameter;
        
        [DataMemberAttribute()]
        public string next_parameter;
        
        [DataMemberAttribute()]
        public string previous_parameter;
        
        [DataMemberAttribute()]
        public int start;
        
        [DataMemberAttribute()]
        public int total;
        
        [DataMemberAttribute()]
        public SensorListEntry[] lists;
    }

    // Type created for JSON at <<root>> --> message --> lists
    [DataContractAttribute(Name="lists")]
    public partial class SensorListEntry
    {
        
        [DataMemberAttribute()]
        public int sensorsID;
        
        [DataMemberAttribute()]
        public int sensorstokenID;
        
        [DataMemberAttribute()]
        public string sensorCompany;
        
        [DataMemberAttribute()]
        public string sensorDeviceID;
        
        [DataMemberAttribute()]
        public string firmwareVersion;
        
        [DataMemberAttribute()]
        public string sensorName;
        
        [DataMemberAttribute()]
        public string isAllocated;

        [IgnoreDataMember]
        public Boolean Allocated 
        { 
            get 
            { 
                return (isAllocated == "Y") ? true: false; 
            } 
        }
        
        [DataMemberAttribute()]
        public string description;
        
        [DataMemberAttribute()]
        public int companyID;
        
        [DataMemberAttribute()]
        public int createdDate;
        
        [DataMemberAttribute()]
        public int updatedDate;
        
        [DataMemberAttribute()]
        public int createdByUserID;
        
        [DataMemberAttribute()]
        public int updatedByUserID;
        
        [DataMemberAttribute()]
        public object latest_sensorsdata;
    }
}